name: Trigger DevOps Workflow 

# on:
#  push:
#    branches:
#      - main
on:
   workflow_dispatch:

jobs:
  trigger-devops:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Enviar solicitud HTTP a la API de GitHub
      - name: Trigger DevOps Workflow via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/DevOps-StellaFontoura/DevOps/dispatches \
          -d '{"event_type": "test-event", "client_payload": {"repository": "${{ github.repository }}", "branch": "${{ github.ref_name }}"}}'
